
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asif
 */
public class myAccount extends javax.swing.JFrame {

    /**
     * Creates new form myAccount
     */
    private static final String USERNAME="root";
    private static final String PASSWORD="";
    private static final String CONN_STRING="jdbc:mysql://localhost:3306/family";
    public String usr;
    public String psw;
    public myAccount() {
        //this.usr=uname;
        //this.psw=pswd;
        getusr_pswd();
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        //display account panel visible
        display_acc.setEnabled(true);
        display_acc.setVisible(true);
        new_pswd_panel.setEnabled(false);
        new_pswd_panel.setVisible(false);        
    }
    
    void getusr_pswd()
    {
        homepage hm = new homepage();
        this.usr = homepage.user;
        System.out.println("usr :"+usr);
        this.psw = homepage.pswd;
        System.out.println("psw :"+psw);
    }
    
    void Connection()
    {
       Connection conn = null;
        try
        {
            conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            System.out.println("Connection successful");
            String sql = "select * from newuser1 where username=? and password=?";
            PreparedStatement st = conn.prepareStatement(sql);
            //homepage hp = new homepage();
            st.setString(1, usr);
            st.setString(2, psw);
            ResultSet rs = st.executeQuery();
            System.out.println("username:"+usr);
            System.out.println("last line");
            if(rs.next())
            {
                String sql1 = "select firstname,lastname,username,password from newuser1 where username=st.setString and password=st.setString";
                PreparedStatement st1=conn.prepareStatement(sql1);
                ResultSet rs1 = st.getResultSet();
                fname_txt.setText(rs1.getString("firstname"));
                lname_txt.setText(rs1.getString("lastname"));
                uname_txt.setText(rs1.getString("username"));
                pswd_txt.setText(rs1.getString("password"));
            }
            else
                {
                    JOptionPane.showMessageDialog(null,"Values not displayed","Error", JOptionPane.ERROR_MESSAGE);
                }
            conn.close();
            System.out.println("Connection closed for displaying acc details");
        }
        catch(Exception e)
        {
            System.out.println("Connection problem");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display_acc = new javax.swing.JPanel();
        del_acc_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        new_pswd_panel = new javax.swing.JPanel();
        ok_button = new javax.swing.JButton();
        new_pswd_field = new javax.swing.JTextField();
        new_pswd_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pswd_change_label = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        header_label = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        pswd = new javax.swing.JLabel();
        fname_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        uname_txt = new javax.swing.JTextField();
        pswd_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display_acc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        del_acc_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        del_acc_button.setText("Click Here to Delete Account");
        del_acc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_acc_buttonActionPerformed(evt);
            }
        });
        display_acc.add(del_acc_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 270, -1));

        back_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        display_acc.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 470, 100, -1));

        new_pswd_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });
        new_pswd_panel.add(ok_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));
        new_pswd_panel.add(new_pswd_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 140, 30));

        new_pswd_label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        new_pswd_label.setForeground(new java.awt.Color(255, 255, 255));
        new_pswd_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        new_pswd_label.setText("NEW PASSWORD");
        new_pswd_panel.add(new_pswd_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Make It Personal\\1080p\\HD\\Black-Background-Collapsar-by-Freeman.jpg")); // NOI18N
        new_pswd_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        display_acc.add(new_pswd_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 350, 80));

        pswd_change_label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pswd_change_label.setForeground(new java.awt.Color(255, 255, 255));
        pswd_change_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pswd_change_label.setText("Click here to change Password");
        pswd_change_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pswd_change_labelMouseClicked(evt);
            }
        });
        display_acc.add(pswd_change_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 320, 20));

        fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fname.setText("FIRST NAME");
        display_acc.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 99, 149, 31));

        header_label.setBackground(new java.awt.Color(102, 102, 102));
        header_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        header_label.setForeground(new java.awt.Color(255, 255, 255));
        header_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_label.setText("ACCOUNT DETAILS");
        display_acc.add(header_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 81));

        lname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lname.setText("LAST NAME");
        display_acc.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 148, 149, 31));

        uname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uname.setText("USER NAME");
        display_acc.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 197, 149, 31));

        pswd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pswd.setForeground(new java.awt.Color(255, 255, 255));
        pswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pswd.setText("PASSWORD");
        display_acc.add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 246, 149, 31));
        display_acc.add(fname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 99, 148, 31));
        display_acc.add(lname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 148, 148, 31));
        display_acc.add(uname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 197, 148, 31));
        display_acc.add(pswd_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 246, 148, 31));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Make It Personal\\1080p\\HD\\Black-Background-Collapsar-by-Freeman.jpg")); // NOI18N
        display_acc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 510));

        jPanel1.add(display_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 520, 510));

        main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main.setIcon(new javax.swing.ImageIcon("E:\\SEM 5\\srp\\photos\\background.PNG")); // NOI18N
        jPanel1.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pswd_change_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswd_change_labelMouseClicked
        // TODO add your handling code here:
        new_pswd_panel.setEnabled(true);
        new_pswd_panel.setVisible(true);
    }//GEN-LAST:event_pswd_change_labelMouseClicked

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void del_acc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_acc_buttonActionPerformed
        // TODO add your handling code here:
        Connection conn1 = null;
        try
        {
            conn1 = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            System.out.println("Connection successful");
            Statement stm = conn1.createStatement();
            if(JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
            {
                System.out.println("delete query in execution");
                System.out.println("usr:"+usr);
                stm.executeUpdate("DELETE FROM newuser1 WHERE username='"+uname_txt.getText()+"'");
                System.out.println("delete query executed");
                JOptionPane.showMessageDialog(null,"Your Account has been deleted", "Account deletion", JOptionPane.PLAIN_MESSAGE);
                stm.close(); 
                fname_txt.setText("");
                lname_txt.setText("");
                uname_txt.setText("");
                pswd_txt.setText("");
            }
            conn1.close();
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,"Unable to delete account.Try Again","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_del_acc_buttonActionPerformed

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        // TODO add your handling code here:
        Connection conn1 = null;
        try
        {
            conn1 = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            System.out.println("Connection successful");
            Statement stm = conn1.createStatement();
            stm.executeUpdate("update newuser1 set password='"+new_pswd_field.getText()+"' where username='"+uname_txt.getText()+"'");
            System.out.println("update query executed");
            pswd_txt.setText(new_pswd_field.getText());
            JOptionPane.showMessageDialog(null,"Your Password has been updated", "Updation successful", JOptionPane.PLAIN_MESSAGE);
            stm.close();
            conn1.close();
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null,"Unable to delete account.Try Again","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
        new_pswd_panel.setEnabled(false);
        new_pswd_panel.setVisible(false);
    }//GEN-LAST:event_ok_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new myAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton del_acc_button;
    private javax.swing.JPanel display_acc;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JLabel header_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JLabel main;
    private javax.swing.JTextField new_pswd_field;
    private javax.swing.JLabel new_pswd_label;
    private javax.swing.JPanel new_pswd_panel;
    private javax.swing.JButton ok_button;
    private javax.swing.JLabel pswd;
    private javax.swing.JLabel pswd_change_label;
    private javax.swing.JTextField pswd_txt;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField uname_txt;
    // End of variables declaration//GEN-END:variables
}
